### ISSUE TITLE
Add support for custom SSL context and read system certs by default

### ISSUE THREAD

**Issue by zoido** [h2oai/cloud-discovery-py#100]
Reading from system cert store is useful when you have private CA. Allowing to pass arbitrary SSL context as well but also can help with testing with private CA or when you need to not verify cert.

**Comment by this** [comment]
I'm not sure introducing `ssl_verify: bool`, `ssl_ca_cert: str` params would fix the issue reported in https://h2oai.slack.com/archives/C07580BBGSH/p1721128898831239 and https://github.com/h2oai/ai-engine-manager/issues/1576. However we need to introduce them because we have customer's like CBA who uses their own CA certs, which would causes to occur CA cert issues unless we have a way to set the cert.

@zoido Please prioritize this feature request. cc @bilcus @codyharris-h2o-ai
